### ISSUE TITLE
Set up automatic docker builds and add docker pull to README

### ISSUE THREAD

**Issue by audip** [V3ckt0r/fluentd_exporter#3]
As discussed in the PR comments, a **feature request** for this image to be publically available on Docker Hub that way one can `docker run <author>/<container-image>:<tag>` to pull and start using `fluentd-exporter` without having to build the image themselves.

The addition of the image to readme will be beneficial and only those who make changes to the code will need to build image for themselves.

**Comment by V3ckt0r** [comment]
Yea that's cool. I will take a look at this.

**Comment by V3ckt0r** [comment]
linking PR for docker CI #5

**Comment by V3ckt0r** [comment]
Successful CI builds now push to docker hub https://hub.docker.com/r/vect0r/fluentd_exporter/

**Comment by audip** [comment]
Thank you. 🎉
