### ISSUE TITLE
Use alpine as base image for docker 

### ISSUE THREAD

**Issue by ghost** [V3ckt0r/fluentd_exporter#6]
Current `golang:1.8` image is huge for a simple exporter application, using `alpine` based image will reduce size from 276 MB to 83 MB.
I'm not much familiar with golang compatibility across different version and distributions so I don't change it myself.

**Comment by V3ckt0r** [comment]
Hey @k1-hedayati,

I've updated the base image to use golang:1.10.1-alpine, this has brought the image size down. See [here](https://github.com/V3ckt0r/fluentd_exporter/commit/f750c760ff96b93bb9e83f99020af0882d860b9f).

Cheers.

**Comment by ghost** [comment]
Thank you @V3ckt0r, feel free to close this issue when ever you wish
