### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by paulfantom** [V3ckt0r/fluentd_exporter#8]
It would be nice to include binary releases in assets section of https://github.com/V3ckt0r/fluentd_exporter/releases

**Comment by V3ckt0r** [comment]
hey @paulfantom,

Sure thing, I'll drop them in. Which binary releases are you interested in?

Cheers,

**Comment by paulfantom** [comment]
latest (0.2.0) would be nice

**Comment by V3ckt0r** [comment]
hey @paulfantom,

I've updated the assets against release 0.2.0. See https://github.com/V3ckt0r/fluentd_exporter/releases/tag/0.2.0

I'll close this issue out now. Feel free to raise if there is anything else.

Cheers.

**Comment by paulfantom** [comment]
So many platforms... Thanks! :+1:
